// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: proto/grader.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LanguageType int32

const (
	LanguageType_CPP    LanguageType = 0
	LanguageType_C      LanguageType = 1
	LanguageType_GO     LanguageType = 2
	LanguageType_PYTHON LanguageType = 3
)

// Enum value maps for LanguageType.
var (
	LanguageType_name = map[int32]string{
		0: "CPP",
		1: "C",
		2: "GO",
		3: "PYTHON",
	}
	LanguageType_value = map[string]int32{
		"CPP":    0,
		"C":      1,
		"GO":     2,
		"PYTHON": 3,
	}
)

func (x LanguageType) Enum() *LanguageType {
	p := new(LanguageType)
	*p = x
	return p
}

func (x LanguageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LanguageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_grader_proto_enumTypes[0].Descriptor()
}

func (LanguageType) Type() protoreflect.EnumType {
	return &file_proto_grader_proto_enumTypes[0]
}

func (x LanguageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LanguageType.Descriptor instead.
func (LanguageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_grader_proto_rawDescGZIP(), []int{0}
}

type ResultType int32

const (
	ResultType_COMPILATION_ERROR     ResultType = 0
	ResultType_PASS                  ResultType = 1
	ResultType_INCORRECT             ResultType = 2
	ResultType_RUNTIME_ERROR         ResultType = 3
	ResultType_TIME_LIMIT_EXCEEDED   ResultType = 4
	ResultType_MEMORY_LIMIT_EXCEEDED ResultType = 5
)

// Enum value maps for ResultType.
var (
	ResultType_name = map[int32]string{
		0: "COMPILATION_ERROR",
		1: "PASS",
		2: "INCORRECT",
		3: "RUNTIME_ERROR",
		4: "TIME_LIMIT_EXCEEDED",
		5: "MEMORY_LIMIT_EXCEEDED",
	}
	ResultType_value = map[string]int32{
		"COMPILATION_ERROR":     0,
		"PASS":                  1,
		"INCORRECT":             2,
		"RUNTIME_ERROR":         3,
		"TIME_LIMIT_EXCEEDED":   4,
		"MEMORY_LIMIT_EXCEEDED": 5,
	}
)

func (x ResultType) Enum() *ResultType {
	p := new(ResultType)
	*p = x
	return p
}

func (x ResultType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResultType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_grader_proto_enumTypes[1].Descriptor()
}

func (ResultType) Type() protoreflect.EnumType {
	return &file_proto_grader_proto_enumTypes[1]
}

func (x ResultType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResultType.Descriptor instead.
func (ResultType) EnumDescriptor() ([]byte, []int) {
	return file_proto_grader_proto_rawDescGZIP(), []int{1}
}

type Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     string       `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Language LanguageType `protobuf:"varint,3,opt,name=language,proto3,enum=main.LanguageType" json:"language,omitempty"`
	TaskId   uint32       `protobuf:"varint,4,opt,name=taskId,proto3" json:"taskId,omitempty"`
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_proto_grader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_proto_grader_proto_rawDescGZIP(), []int{0}
}

func (x *Input) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Input) GetLanguage() LanguageType {
	if x != nil {
		return x.Language
	}
	return LanguageType_CPP
}

func (x *Input) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result ResultType `protobuf:"varint,1,opt,name=result,proto3,enum=main.ResultType" json:"result,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_proto_grader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_grader_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetResult() ResultType {
	if x != nil {
		return x.Result
	}
	return ResultType_COMPILATION_ERROR
}

var File_proto_grader_proto protoreflect.FileDescriptor

var file_proto_grader_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x63, 0x0a, 0x05, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x6c,
	0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22,
	0x32, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x28, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x2a, 0x32, 0x0a, 0x0c, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x50, 0x50, 0x10, 0x00, 0x12, 0x05, 0x0a, 0x01,
	0x43, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x47, 0x4f, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x50,
	0x59, 0x54, 0x48, 0x4f, 0x4e, 0x10, 0x03, 0x2a, 0x83, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x4f, 0x4d, 0x50, 0x49, 0x4c,
	0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x50, 0x41, 0x53, 0x53, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x4e, 0x43, 0x4f, 0x52,
	0x52, 0x45, 0x43, 0x54, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x55, 0x4e, 0x54, 0x49, 0x4d,
	0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x17, 0x0a, 0x13, 0x54, 0x49, 0x4d,
	0x45, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f, 0x45, 0x58, 0x43, 0x45, 0x45, 0x44, 0x45, 0x44,
	0x10, 0x04, 0x12, 0x19, 0x0a, 0x15, 0x4d, 0x45, 0x4d, 0x4f, 0x52, 0x59, 0x5f, 0x4c, 0x49, 0x4d,
	0x49, 0x54, 0x5f, 0x45, 0x58, 0x43, 0x45, 0x45, 0x44, 0x45, 0x44, 0x10, 0x05, 0x32, 0x30, 0x0a,
	0x06, 0x47, 0x72, 0x61, 0x64, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x05, 0x47, 0x72, 0x61, 0x64, 0x65,
	0x12, 0x0b, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x0c, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x30, 0x01, 0x42,
	0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x65,
	0x65, 0x70, 0x41, 0x75, 0x6e, 0x67, 0x2f, 0x67, 0x72, 0x61, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x2f,
	0x67, 0x72, 0x61, 0x64, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_grader_proto_rawDescOnce sync.Once
	file_proto_grader_proto_rawDescData = file_proto_grader_proto_rawDesc
)

func file_proto_grader_proto_rawDescGZIP() []byte {
	file_proto_grader_proto_rawDescOnce.Do(func() {
		file_proto_grader_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_grader_proto_rawDescData)
	})
	return file_proto_grader_proto_rawDescData
}

var file_proto_grader_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_grader_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_grader_proto_goTypes = []any{
	(LanguageType)(0), // 0: main.LanguageType
	(ResultType)(0),   // 1: main.ResultType
	(*Input)(nil),     // 2: main.Input
	(*Result)(nil),    // 3: main.Result
}
var file_proto_grader_proto_depIdxs = []int32{
	0, // 0: main.Input.language:type_name -> main.LanguageType
	1, // 1: main.Result.result:type_name -> main.ResultType
	2, // 2: main.Grader.Grade:input_type -> main.Input
	3, // 3: main.Grader.Grade:output_type -> main.Result
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_grader_proto_init() }
func file_proto_grader_proto_init() {
	if File_proto_grader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_grader_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_grader_proto_goTypes,
		DependencyIndexes: file_proto_grader_proto_depIdxs,
		EnumInfos:         file_proto_grader_proto_enumTypes,
		MessageInfos:      file_proto_grader_proto_msgTypes,
	}.Build()
	File_proto_grader_proto = out.File
	file_proto_grader_proto_rawDesc = nil
	file_proto_grader_proto_goTypes = nil
	file_proto_grader_proto_depIdxs = nil
}
